### ISSUE TITLE
Support negative tests

### ISSUE THREAD

**Issue by Hoblovski** [rcore-os/zCore#103]
Add negative tests to the original test suite.

Description:
* Example: if the test program does not have access privilege to some IO port, then it is expected that **issuing the in/out on that port causes a #GP exception**

Depends on:
* [ ] Exception Channel

**Comment by wangrunji0408** [comment]
Exception channel is now available. #101

**Comment by benpigchu** [comment]
Exception channel is now partially available, but if the test is using a debug exception channel, it still do not works for now.
See #68 .
