### ISSUE TITLE
what is git lfs?

### ISSUE THREAD

**Issue by mitnk** [rcore-os/zCore#11]
In readme, there is `git lfs` command. It's not a git command.

Do you mean something like `git submodule update --init` ?

**Comment by wangrunji0408** [comment]
It is [Git Large File Storage](https://git-lfs.github.com).

You can install it by:
```sh
# Linux
sudo apt install git-lfs
# macOS
brew install git-lfs
# then setup
git lfs install
```

We use it to store large prebuilt images of Fuchsia.

**Comment by mitnk** [comment]
Ah, thanks. I guess it’s better to be added into readme, or same issues would be created in future.
