### ISSUE TITLE
[discuss] Using libc-test for zcore linux LibOS on Ubuntu 20.04

### ISSUE THREAD

**Issue by yunwei37** [rcore-os/zCore#134]
I can run libc-test on zcore linux LibOS now, maybe I should create a new pull-request with a new branch on rCore/libc-test repo for customizations makefile ? （ but it seems I cannot create a new branch on pull-request... ）

Also, I will write a makefile or script for automatic test and report in zCore, maybe the method of running tests can be add to the main README.md like zircon test ?

**Comment by wangrunji0408** [comment]
Resolved by #151
