### ISSUE TITLE
Did not find ELF magic number

### ISSUE THREAD

**Issue by goodforever** [rcore-os/zCore#175]
on Mac OS run
cargo run --release -p zircon-loader prebuilt/zircon/x64

got error:

     Running `target/release/zircon-loader prebuilt/zircon/x64`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Did not find ELF magic number"', /Users/foo/rust/zCore/zircon-loader/src/lib.rs:58:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by yunwei37** [comment]
You can refer to (#52 )[https://github.com/rcore-os/zCore/issues/52], it's the same problem we haven't fixed...

Maybe we can consider remove this command in the README temporarily?

**Comment by wangrunji0408** [comment]
Did you miss the LFS setup?
```
git lfs install
git lfs pull
```

**Comment by goodforever** [comment]
Thnaks !, I missed "git lfs pull"  but after run , then 
cargo run --release -p zircon-loader prebuilt/zircon/x64

I failed 

log 
bootsvc: Loading boot arguments...
userboot: finished!
bootsvc: Creating svcfs service...
bootsvc: Loading kernel VMOs...
bootsvc: Creating loader service...
bootsvc: Launching next process...
bootsvc: bootsvc.next = bin/component_manager,fuchsia-boot:///#meta/root.cm,--config-file,/boot/config/component_manager,--use-builtin-process-launcher,--maintain-utc-clock
bootsvc: Launched bin/component_manager
[component_manager] INFO: Component manager is starting up...
[component_manager] INFO: Loaded runtime config from /boot/config/component_manager
fshost: watching for exit
Bus error: 10
