### ISSUE TITLE
Build zCore kernel failed

### ISSUE THREAD

**Issue by maxre404** [rcore-os/zCore#22]
OS: macOS 10.15.4 

shuais@Macintosh zCore % cd zCore && make run mode=release
echo Building zCore kenel
Building zCore kenel
cargo build -Z build-std=core,alloc --target x86_64.json --release
    Updating git repository `https://github.com/rcore-os/bitmap-allocator`
    Updating crates.io index
    Updating git repository `https://github.com/PanQL/executor.git`
error: failed to get `rboot` as a dependency of package `zcore v0.1.0 (/Users/shuais/zCore/zCore)`

Caused by:
  failed to load source for dependency `rboot`

Caused by:
  Unable to update /Users/shuais/zCore/rboot

Caused by:
  failed to read `/Users/shuais/zCore/rboot/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
make: *** [kernel] Error 101

**Comment by wangrunji0408** [comment]
Seems you didn't initialize submodules. Try:
```sh
git submodule update --init
```

**Comment by maxre404** [comment]
it works ,but a new problem has appeared

BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00003 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Secondary,Master,0x0): Not Found
BdsDxe: loading Boot0002 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Primary,Master,0x0)
BdsDxe: starting Boot0002 "UEFI QEMU HARDDISK QM00001 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Primary,Master,0x0)
INFO: bootloader is running
INFO: opening file: \EFI\Boot\rboot.conf
INFO: loading file to memory
INFO: switching graphic mode
INFO: config: Config {
INFO:     kernel_stack_address: 0xffffff0100000000,
INFO:     kernel_stack_size: 0x200,
INFO:     physical_memory_offset: 0xffff800000000000,
INFO:     kernel_path: "\\EFI\\zCore\\zcore.elf",
INFO:     resolution: Some(
INFO:         (
INFO:             0x400,
INFO:             0x300,
INFO:         ),
INFO:     ),
INFO:     initramfs: Some(
INFO:         "\\EFI\\zCore\\fuchsia.zbi",
INFO:     ),
INFO:     cmdline: "LOG=error",
INFO: }
INFO: acpi2: 0xbfbfa014
INFO: opening file: \EFI\zCore\zcore.elf
INFO: loading file to memory
INFO: opening file: \EFI\zCore\fuchsia.zbi
INFO: loading file to memory
INFO: mapping ELF
INFO: mapping stack at 0xffffff0100000000
INFO: mapping physical memory
INFO: exit boot services
userboot: option "LOG=error"
userboot: option "console.shell=true"
[12.116067343s ERROR 0:0] Enlarging heap to avoid oom
[12.117446326s ERROR 0:0] 

panicked at 'index out of bounds: the len is 32 but the index is 32', src/memory.rs:99:9
[12.117959s ERROR 0:0] KCounters {
    "exceptions.user": 47,
    "exceptions.timer": 4,
    "exceptions.pgfault": 0,
    "Channel.create": 2,
    "Channel.destroy": 2,
    "vmo.page_alloc": 97953,
    "vmo.page_dealloc": 0,
    "VmObject.create": 14,
    "VmObject.destroy": 0,
    "EventPair.create": 0,
    "EventPair.destroy": 0,
    "Thread.create": 1,
    "Thread.destroy": 0,
    "Event.create": 0,
    "Event.destroy": 0,
    "Timer.create": 0,
    "Timer.destroy": 0,
    "VmAddressRegion.create": 12,
    "VmAddressRegion.destroy": 0,
    "Job.create": 1,
    "Job.destroy": 0,
    "Process.create": 2,
    "Process.destroy": 0,
}

**Comment by wangrunji0408** [comment]
Sorry, we updated a dependence crate and accidentally broke the old version.
Pull the latest master branch then try again.

**Comment by maxre404** [comment]
> Sorry, we updated a dependence crate and accidentally broke the old version.
> Pull the latest master branch then try again.

ok  thanks
