### ISSUE TITLE
Suggestions for improving github CI

### ISSUE THREAD

**Issue by shzhxh** [rcore-os/zCore#250]
1. 针对整体任务测试时间过长的问题，降低整体测试时间

- [x]    1. 提高并行性，具体方法是拆解时间过长的任务
- [x]    2. 减少冗余环节

2. 针对测试任务输出过多的问题，减少无效输出

- [x]    1. 对于测试失败的案例输出详情，对于测试成功的案例只输出"xxx PASSED"

3. 其它

- [x] 1. 当无输出的时候，会判定为通过，但实际上应判定为超时
- [x] 2. 内核开发者一般不需要修改测试代码。为避免内核开发者即当运动员，又当裁判员的情况出现，建议测试代码作为相对独立的子模块出现。
- [ ] 3. 每一个提交都应该被测试。但如果一个pr里包含多个提交，则只有最近的一个提交被测试。所以测试代码里应加入检测的逻辑，阻止一个pr里包含多个提交的情况。

**Comment by elliott10** [comment]
减少不必要的测试action，例如现在好像有编译ARM交叉工具链的ci

**Comment by shzhxh** [comment]
> 减少不必要的测试action，例如现在好像有编译ARM交叉工具链的ci

好，关于此点我会注意。

**Comment by shzhxh** [comment]
相关的代码在https://github.com/shzhxh/zCore，master-szx分支。主要的修改是：
1. 把测试脚本作为子模块(tests子模块)出现，目的是避免3.2的问题。
2. 在测试脚本里非阻塞地读取管道中的信息，目的是解决问题1里提出的测试时间过长的问题。
3. 在测试案例里把oscomp从libc里分离出来。
4. 无输出时被判定为超时，目的是解决3.1的问题。
