### ISSUE TITLE
The "uname" command shows up incorrect results

### ISSUE THREAD

**Issue by wangyisong1996** [rcore-os/zCore#26]
* Ubuntu 20.04 Desktop (64 bit)
* `rustup 1.21.1 (7832b2ebe 2019-12-20)`
* `rustc 1.44.0-nightly (b543afca9 2020-04-05)`
* Followed `README.md` to build zCore
* Run `cargo run --release -p linux-loader /bin/busybox uname -a`
* Got the result
`rCore orz 0.1.0 1 machine Linux`

Should zCore kernel have a uname starting with `zCore`?

**Comment by yunwei37** [comment]
It seems the uname string is hard-coded：

in `linux-syscall/src/misc.rs`

```
pub fn sys_uname(&self, buf: UserOutPtr<u8>) -> SysResult {
        info!("uname: buf={:?}", buf);

        let strings = ["rCore", "orz", "0.1.0", "1", "machine", "domain"];
        for (i, &s) in strings.iter().enumerate() {
            const OFFSET: usize = 65;
            buf.add(i * OFFSET).write_cstring(s)?;
        }
        Ok(0)
    }

```

**Comment by wangrunji0408** [comment]
The uname should start with `Linux` because some programs will check this field.
