### ISSUE TITLE
CANNOT run "ls" as a native linux program

### ISSUE THREAD

**Issue by wangyisong1996** [rcore-os/zCore#27]
* Ubuntu 20.04 Desktop (64 bit)
* `rustup 1.21.1 (7832b2ebe 2019-12-20)`
* `rustc 1.44.0-nightly (b543afca9 2020-04-05)`
* Followed `README.md` to build zCore
* Run `cargo run --release -p linux-loader /bin/busybox ls`
* Got the result
```
$ cargo run --release -p linux-loader /bin/busybox ls
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/linux-loader /bin/busybox ls`
[ERROR][1] unknown syscall: 228. exit...
```

Is there anything missing in zCore kernel?

**Comment by jiegec** [comment]
228: SYS_CLOCK_GETTIME on x86_64

**Comment by jiegec** [comment]
See #28
