### ISSUE TITLE
RISC-V 多核启动失败

### ISSUE THREAD

**Issue by YdrMaster** [rcore-os/zCore#281]
最新的 master RISC-V 多核启动失败。通过初步的调试，可能是 `kernel-hal/src/bare/arch/riscv/mod.rs` 的 `secondary_init` 函数工作不正常。

**Comment by elliott10** [comment]
相关commit: https://github.com/rcore-os/zCore/commit/3559a39b1fa35dd06d8ae08642c316f87fac44ed

**Comment by yuzc19** [comment]
make LOG=INFO 发现卡死在 intc handle irq, cause 5 这里（表现不稳定，有的时候不是这里）

**Comment by elliott10** [comment]
patch降低了卡住的几率，但依然有卡住的问题

**Comment by YdrMaster** [comment]
目前[这个依赖](https://github.com/DeathWish5/kernel-sync.git)可能面临频繁修改，没有写 `rev`，需要在编译前 `cargo update`。
