### ISSUE TITLE
Panic when run `make image ARCH=riscv64`

### ISSUE THREAD

**Issue by shzhxh** [rcore-os/zCore#295]
the panic is as follows:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" }', xtask/src/download.rs:19:30

When change `fs::rename` to `fs::copy` in the line where the error was reported, the error disappeared.
Document of Rust STD library shows that `std::fs::rename` will not work if the new name is on a different mount point. And I tested it locally, it does report the same error when I rename file to a different mount point.

**Comment by YdrMaster** [comment]
了解了，确实原理上 rename 不可能跨 mount。不过 CI 没问题，是因为 CI 的文件系统整个都是虚拟出来的，都和 /tmp 在一起？

**Comment by YdrMaster** [comment]
我本地 wget 下载这些东西很难成功，所以测试不够充分……

**Comment by shzhxh** [comment]
是的，猜测github CI上/tmp只是一个普通目录，没有挂载为内存文件系统。
