### ISSUE TITLE
Could not compile & run.

### ISSUE THREAD

**Issue by 0400H** [rcore-os/zCore#317]
Env:

Ubuntu18.04 docker
rustc 1.60.0-nightly (5e57faa78 2022-01-19)
commit [fd67f173df1404fb805818e41ca97898deedb0c1](https://github.com/rcore-os/zCore/tree/fd67f173df1404fb805818e41ca97898deedb0c1)

----

[Run zcore in linux-libos mode](https://github.com/rcore-os/zCore#run-zcore-in-linux-libos-mode)
```
step 2: Compile & Run native Linux program (Busybox) in libos mode:
cargo run --release --features "linux libos" -- /bin/busybox [args]
```
type
```
cargo run --release --features "linux libos" -- /bin/busybox ls
```
get
```
error: none of the selected packages contains these features: libos, linux
```
____

[Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
```
step 2: Create Linux rootfs image:
Note: Before below step, you can add some special apps in zCore/rootfs
make image
```
type
```
make image
```
get
```
cargo image --arch x86_64
warning: unused import: `ffi::OsStr`
 --> xtask/src/linux/opencv.rs:7:5
  |
7 |     ffi::OsStr,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `xtask` (bin "xtask") generated 1 warning
    Finished release [optimized + debuginfo] target(s) in 0.12s
     Running `target/release/xtask image --arch x86_64`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', xtask/src/command/mod.rs:50:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0400H** [comment]
Fix `README.md` errors?
Provide a base docker image for developer?
Provide some `git tag` for stable `git commit`?

**Comment by YdrMaster** [comment]
先试试 qemu？`cargo qemu --arch riscv64` 或者 `cargo qemu --arch aarch64` 肯定可以（当然，需要先安装 qemu）。目前 libos 主要用来单元测试，启动接 bash 还需要整理。
可以看这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)（注意 make setup）。

**Comment by YdrMaster** [comment]
> [Run zcore in linux-libos mode](https://github.com/rcore-os/zCore#run-zcore-in-linux-libos-mode)
> 
> ```
> step 2: Compile & Run native Linux program (Busybox) in libos mode:
> cargo run --release --features "linux libos" -- /bin/busybox [args]
> ```
> 
> type
> 
> ```
> cargo run --release --features "linux libos" -- /bin/busybox ls
> ```
> 
> get
> 
> ```
> error: none of the selected packages contains these features: libos, linux
> ```
> 
> [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> 
> ```
> step 2: Create Linux rootfs image:
> Note: Before below step, you can add some special apps in zCore/rootfs
> make image
> ```
> 
> type
> 
> ```
> make image
> ```
> 
> get
> 
> ```
> cargo image --arch x86_64
> warning: unused import: `ffi::OsStr`
>  --> xtask/src/linux/opencv.rs:7:5
>   |
> 7 |     ffi::OsStr,
>   |     ^^^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> warning: `xtask` (bin "xtask") generated 1 warning
>     Finished release [optimized + debuginfo] target(s) in 0.12s
>      Running `target/release/xtask image --arch x86_64`
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', xtask/src/command/mod.rs:50:32
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

libos 模式需要 `cd zCore` 再 `cargo run --release --features "linux libos" -- /bin/busybox [args]`

**Comment by 0400H** [comment]
> 先试试 qemu？`cargo qemu --arch riscv64` 或者 `cargo qemu --arch aarch64` 肯定可以（当然，需要先安装 qemu）。目前 libos 主要用来单元测试，启动接 bash 还需要整理。 可以看这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)（注意 make setup）。

目前还没有还没有尝试QEMU执行。
看过这个文档，但是LibOS模式还是不能编译，能提供一个commit吗？
对于LibOS模式建议使用容器来标准化开发环境，也方便测试。
以后定期打Tag可能比较方便Checkout。

**Comment by YdrMaster** [comment]
> > 先试试 qemu？`cargo qemu --arch riscv64` 或者 `cargo qemu --arch aarch64` 肯定可以（当然，需要先安装 qemu）。目前 libos 主要用来单元测试，启动接 bash 还需要整理。 可以看这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)（注意 make setup）。
> 
> 目前还没有尝试去配置QEMU环境和执行（没找到说明文档）. 看过这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)，但是LibOS模式还是不能编译，能提供一个commit吗？ 对于LibOS模式建议使用容器来标准化开发环境，也方便测试。 以后定期打Tag可能比较方便Checkout。

等明天 pr #322 合了再试试吧。libos 就是为了直接跑，什么都不用配才做的，qemu 实际也很方便了。

1. [下载](https://www.qemu.org/)，建议 7.0.0，不能早于 6.1.0
2. 安装
   ```bash
   tar xf qemu.tar.xz
   cd qemu
   ./configure --target-list=x86_64-softmmu,riscv64-softmmu,aarch64-softmmu
   make -j
   sudo make install
   ```

**Comment by 0400H** [comment]
> > > 先试试 qemu？`cargo qemu --arch riscv64` 或者 `cargo qemu --arch aarch64` 肯定可以（当然，需要先安装 qemu）。目前 libos 主要用来单元测试，启动接 bash 还需要整理。 可以看这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)（注意 make setup）。
> > 
> > 
> > 目前还没有尝试去配置QEMU环境和执行（没找到说明文档）. 看过这个[文档](https://github.com/rcore-os/zCore/blob/master/docs/Manual.md)，但是LibOS模式还是不能编译，能提供一个commit吗？ 对于LibOS模式建议使用容器来标准化开发环境，也方便测试。 以后定期打Tag可能比较方便Checkout。
> 
> 等明天 pr #322 合了再试试吧。libos 就是为了直接跑，什么都不用配才做的，qemu 实际也很方便了。
> 
> 1. [下载](https://www.qemu.org/)，建议 7.0.0，不能早于 6.1.0
> 2. 安装
>    ```shell
>    tar xf qemu.tar.xz
>    cd qemu
>    ./configure --target-list=x86_64-softmmu,riscv64-softmmu,aarch64-softmmu
>    make -j
>    sudo make install
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    configure 的时候可能会报缺依赖，看 [rcore-Tutorial 文档](https://rcore-os.github.io/rCore-Tutorial-Book-v3/chapter0/5setup-devel-env.html#qemu) 就能解决。
> 
> qemu 安装好之后就可以 `cargo qemu --arch riscv64` 了。

还是无法运行。

Commit `0c37bb3485040d825b2e8281f7016e8c98392ec9`
Env ubuntu 18.04 docker

```
make rootfs
```
[make rootfs error.log](https://github.com/rcore-os/zCore/files/8945852/make.rootfs.log)

是ubuntu 18.04问题？

还是建议使用docker标准化开发环境，这种事情几乎可以避免。

**Comment by YdrMaster** [comment]
> 是ubuntu 18.04问题？

可能是吧，busybox 不能编译。但是这个情况能编译大概率也不能运行。

> 还是建议使用docker标准化开发环境，这种事情几乎可以避免。

或许有时间你可以弄一个。

**Comment by 0400H** [comment]
[PR332](https://github.com/rcore-os/zCore/pull/332)

基于此镜像和最新的文档，跑通了以下运行模式：

1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)

**Comment by YdrMaster** [comment]
> [PR332](https://github.com/rcore-os/zCore/pull/332)
> 
> 基于此镜像和最新的文档，跑通了以下运行模式：
> 
> 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)

我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。

**Comment by 0400H** [comment]
> > [PR332](https://github.com/rcore-os/zCore/pull/332)
> > 基于此镜像和最新的文档，跑通了以下运行模式：
> > 
> > 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> > 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)
> 
> 我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。

20.04和18.04版本都没能跑成LibOS mode，类似于最简单的Hello world，这个理应是支持最广泛的。
18.04我没有去装QEMU，装了之后，以上两种Mode应该也能跑。
20.04根据建议安装了QEMU，以上两种Mode可以跑。

希望如果有时间的话，可以将根目录的[README.md](https://github.com/rcore-os/zCore/blob/master/README.md)按照运行Mode的关联性，分离成各个子README.md
需要重复执行的指令不要节省，按照原样贴出，需要的依赖，按照运行的Mode分别在子README.md中提及就行了，现在看起来相当混乱。

**Comment by 0400H** [comment]
> > [PR332](https://github.com/rcore-os/zCore/pull/332)
> > 基于此镜像和最新的文档，跑通了以下运行模式：
> > 
> > 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> > 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)
> 
> 我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。

对于提PR有什么流程吗？[PR332](https://github.com/rcore-os/zCore/pull/332)是按照常规流程走的，希望能够审阅Merge。

**Comment by 0400H** [comment]
> > [PR332](https://github.com/rcore-os/zCore/pull/332)
> > 基于此镜像和最新的文档，跑通了以下运行模式：
> > 
> > 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> > 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)
> 
> 我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。

```
cargo run --release --features "linux libos" -- /bin/busybox
```
这条LibOS的指令现在是有更新吗？从来没能执行成功过，一直返回
```
error: none of the selected packages contains these features: libos, linux
```

**Comment by YdrMaster** [comment]
[之前发了](https://github.com/rcore-os/zCore/issues/317#issuecomment-1153353255) 需要先 cd zCore。建议看一下我前面的回复。目前 README 已经过时，没有时间改。

**Comment by YdrMaster** [comment]
> > > [PR332](https://github.com/rcore-os/zCore/pull/332)
> > > 基于此镜像和最新的文档，跑通了以下运行模式：
> > > 
> > > 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> > > 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)
> > 
> > 
> > 我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。
> 
> 20.04和18.04版本都没能跑成LibOS mode，类似于最简单的Hello world，这个理应是依赖最少可以直接跑的。 20.04根据建议安装了QEMU，以上两种Mode可以跑。 18.04我没有去装QEMU，装了之后，以上两种Mode应该也能跑。
> 
> 希望如果有时间的话，可以将根目录的[README.md](https://github.com/rcore-os/zCore/blob/master/README.md)按照运行Mode的关联性，分离成各个子README.md 需要重复执行的指令不要节省，按照原样贴出，需要的依赖，按照运行的Mode分别在子README.md中提及就行了，现在看起来相当混乱。

实际上你遇到的问题应该和系统没什么关系。后面发的那个 busybox 无法编译的问题不知道为什么，但理论上啊说也应该和系统无关。

**Comment by YdrMaster** [comment]
> > > [PR332](https://github.com/rcore-os/zCore/pull/332)
> > > 基于此镜像和最新的文档，跑通了以下运行模式：
> > > 
> > > 1. [Run Linux shell in linux-bare-metal mode](https://github.com/rcore-os/zCore#run-linux-shell-in--linux-bare-metal-mode)
> > > 2. [Build and run zcore in zircon-bare-metal mode](https://github.com/rcore-os/zCore#run-zircon-shell-in-zircon-bare-metal-mode)
> > 
> > 
> > 我看这也没什么特别的啊，按你提交的这个配置，系统改成 18 就不行了吗？难以理解。
> 
> 对于提PR有什么流程吗？[PR332](https://github.com/rcore-os/zCore/pull/332)是按照常规流程走的，希望能够审阅Merge。 后续有时间可以提供贡献代码的标准流程README。

有人在看。
