### ISSUE TITLE
update alpine to 3.16

### ISSUE THREAD

**Issue by 1984204066** [rcore-os/zCore#323]
When  make rootfs ARCH=x86_64, it still download alpine 3.12, which is old. 
Why not switch to use newer version 3.16?

Second, how to  setup mirror instead of download directly from https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/, speed is very slow. Or should I directly change source file zcore/xtask/src/main.rs? Is there other way?

**Comment by YdrMaster** [comment]
Upgrading to 3.16 makes boot fail, maybe you're willing to fix this problem？

All the files online will be downloaded to ignored/origin, so you can download them by other way, and put them to the correct path directly. For alphine, set them as `ignored/origin/<arch>/minirootfs.tar.xz`.
