### ISSUE TITLE
升级到 2022/06/17 PR #325 导致缓存失效

### ISSUE THREAD

**Issue by YdrMaster** [rcore-os/zCore#326]
#325 改变了下载的原文件的组织结构，需要修改。

一周后关闭此 issue。

**Comment by elliott10** [comment]
目前遇到几个问题记录如下：
* 在系统已有riscv64编译器时，会重新下载的问题；可考虑重用系统已有编译去；
* 开发过程make clean后，可考虑不再重新编译user程序如opencv，从而快速创建镜像的方法。例如做个说明，在某个目录放置已经prebuilt的文件便可绕过；

**Comment by YdrMaster** [comment]
> 目前遇到几个问题记录如下：
> 
> * 在系统已有riscv64编译器时，会重新下载的问题；可考虑重用系统已有编译去；
> * 开发过程make clean后，可考虑不再重新编译user程序如opencv，从而快速创建镜像的方法。例如做个说明，在某个目录放置已经prebuilt的文件便可绕过；

#330

**Comment by YdrMaster** [comment]
希望大家都已经更新了，或者直接用新的
