### ISSUE TITLE
Support for FU740 board

### ISSUE THREAD

**Issue by elliott10** [rcore-os/zCore#371]
* 基于以前清华童鞋们在fu740开发板适配zCore的工作，运行起来正常进入sh；

* 合并以前代码到zCore master最新分支，大量冲突。修复了：`引导`、`多核启动`、`内存`等系列的问题，在master中正常运行起来；

* 合并后修改以pass测试CI；

* fu740板子的`PCIE`地址在一个超过32位的高地址，对这个问题调整地址空间，并顺利初始化fu740板子的pci扫描功能：

![Screen Shot 2022-09-14 at 12 36 43 PM](https://user-images.githubusercontent.com/8327091/190060801-2151a85e-b0f7-45a0-a0dd-f43f135e83ae.png)

**Comment by shzhxh** [comment]
1. `make fu740 MODE=release LINUX=1 ARCH=riscv64 PLATFORM=fu740`的含义相当于是`make build MODE=release LINUX=1 ARCH=riscv64 PLATFORM=fu740`,没有必要创建新的make对象`fu740`。
2. 需提供`hifive-unmatched-a00.dtb`的生成方式。
3. `make run_d1 ... PLATFORM=d1`的含义相当于是`make run ... PLATFORM=d1`，没有必要创建新的make对象`run_d1`。
4. 在`Cargo.toml`里引用了个人仓库，建议放在`rcore-fs`下。
5. 注意在提交最终pr的时候日志级别调整为Warn。

**Comment by elliott10** [comment]
这些问题重新做了调整合并；

对于fu740对设备树.dtb可以在自带的Linux中的`/boot`目录中获取；
也可以在sifive官方镜像获取：https://github.com/sifive/freedom-u-sdk/releases/download/2022.04.00/demo-coreip-cli-unmatched-2022.04.00.rootfs.wic.xz

**Comment by elliott10** [comment]
继续补充了PCIE的读写函数，包括PCIE与CPU地址转换机制的rust函数实现。
扫描情况：
![WechatIMG412](https://user-images.githubusercontent.com/8327091/198818810-b9db8f56-baa9-4f03-84cc-a1bc1b0d007b.png)
