### ISSUE TITLE
C906/C910的拓展页表设置MAEE该如何关闭？

### ISSUE THREAD

**Issue by sukiiiKotori** [rcore-os/zCore#401]
我在编写自己的操作系统时也遇到了该问题，在zCore文档的C910.md中，我看到开发人员使用了置MAEE为0的方式来关闭平头哥的页表扩展，请问具体该如何关闭呢？非常感谢

**Comment by elliott10** [comment]
需要在M态关闭`mxstatus`寄存器的`MAEE`位。 
具体代码请参考：
https://github.com/elliott10/opensbi/blob/thead_light-c910/platform/generic/platform.c#L61

**Comment by sukiiiKotori** [comment]
> 

非常感谢，但是我们比赛的时候用的是Uboot引导启动，可能没法修改sbi了。那我只能按他的要求设置标志位了

**Comment by elliott10** [comment]
> > 
> 
> 非常感谢，但是我们比赛的时候用的是Uboot引导启动，可能没法修改sbi了。那我只能按他的要求设置标志位了

请问比赛你用的板子型号是？
