### ISSUE TITLE
Implement exception handling

### ISSUE THREAD

**Issue by wangrunji0408** [rcore-os/zCore#68]
Implement the following syscalls:
- [ ] zx_task_create_exception_channel
- [ ] zx_exception_get_thread
- [ ] zx_exception_get_process

Pass core-tests:
- [ ] DefaultExceptionHandlerTest

Reference:
- https://fuchsia.dev/fuchsia-src/concepts/kernel/exceptions

**Comment by benpigchu** [comment]
I will look into this

**Comment by benpigchu** [comment]
Here is some notes on the implementation of exception channel in zircon:

There are two kind of exception channel, normal exception channel and debug exception channel. At the same time, a task can only have one exception channel for each kind.

To implement exception channel, there are two structs: `Exception` and `Exceptionate`. 

The `Exceptionate` is a helper struct owned by the tasks, used to send exceptions to user space. Each task has a normal `Exceptionate` and, if it is process or job, a debug `Exceptionate`. The `Exceptionate` holds the sender end of channel once the exception channel is created

The Exception is the one that was send to userspace. It keeps infomation of the exceptions. The `zx_exception_report` type is also send to the channel. which contains type and context of the exception.

There are different kinds of exceptions. An exception can be triggered not only by hardware exceptions, but also by the kernel when some policy errors was triggered. If the debug exception channel is present, there will be more debug exceptions when the thread or process is starting or exiting.

When a exception was generated, the `Exceptionate`s are tried in this order: Debug -> Thread -> Process -> Debug(the second time) -> Job -> Parent Job ...

The default behavior when the exception is not handled is terminate the thread and the process.

See:
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/system/public/zircon/syscalls/exception.h
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/lib/syscalls/exceptions.cc
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/include/object/exceptionate.h
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/exceptionate.cc
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/include/object/exception_dispatcher.h
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/exception_dispatcher.cc
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/exception.cc
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/include/object/thread_dispatcher.h
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/include/object/process_dispatcher.h
https://fuchsia.googlesource.com/fuchsia/+/master/zircon/kernel/object/include/object/job_dispatcher.h

Also, the `DefaultExceptionHandlerTest` only test the default behavior  when the exception is not handled. More test of exception channel should be in test for tasks.

**Comment by benpigchu** [comment]
Also, there are some more case other generics syscalls to be handled:
- `zx_info_thread` returned by `zx_object_get_info` has a `wait_exception_channel_type` used to indicate if the thread is waiting for the exception handling. Also the `state` field should be `ZX_THREAD_STATE_BLOCKED_EXCEPTION` at this time.
- `zx_exception_report_t` can also be returned by `zx_object_get_info` to get the exception info.
- The process handleing the exception use `zx_object_set_property` to set `ZX_PROP_EXCEPTION_STATE` and `ZX_PROP_EXCEPTION_STRATEGY`

See:
https://fuchsia.dev/fuchsia-src/reference/syscalls/object_get_info#zx_info_thread
https://fuchsia.dev/fuchsia-src/reference/syscalls/object_get_info#zx_info_thread_exception_report
https://fuchsia.dev/fuchsia-src/reference/syscalls/object_get_property#zx_prop_exception_state
https://fuchsia.dev/fuchsia-src/reference/syscalls/object_get_property#zx_prop_exception_strategy

**Comment by benpigchu** [comment]
To be simple, the initial implement of exception channel will:
- do not support debug exception channel
- only support hardware exceptions
- only support x86_64

Basic tests including:
- [ ] `Threads.ThreadStartWithZeroInstructionPointer`
- To be found

**Comment by benpigchu** [comment]
First part of exception channel implementationn is in #101. This is what is left for second part:
- [ ] Send exception to debug exception channel
- [ ] Kernel generated exceptions, including:
  - [ ] `ProcessStarting`
  - [ ] `ThreadStarting`
  - [ ] `PolicyError`
  - [ ] `ThreadExiting`
- [ ] "Shutdown" the `Exceptionate` when the task is terminated
- [ ] Use correct rights for handles returned by `zx_exception_get_*`

**Comment by benpigchu** [comment]
A much more better description of exceptions is in https://fuchsia.dev/fuchsia-src/concepts/kernel/exceptions
Note that some exception can only received from some type of exception channels.

**Comment by benpigchu** [comment]
Core test do not has exception channel test (but it use the exception channel to test other things)
The real exception channel test is in https://fuchsia.googlesource.com/fuchsia/+/master/src/zircon/tests/exception/

**Comment by benpigchu** [comment]
The behviour of the thread state and signals in `Threads.SuspendMultiple` is somehow strange, not like blocking syscalls, a thread block on exception won't suspend!

**Comment by benpigchu** [comment]
Tests from exception-test
- [ ] ExceptionTest
  - [ ] .Trigger
  - [ ] .ExitClosingExcpHandle
  - [ ] .CreateExceptionChannel
  - [ ] .CreateExceptionChannelRights
  - [ ] .CreateExceptionChannelInvalidArgs
  - [ ] .ProcessDebuggerAttached
  - [ ] .ThreadRequiresRights
  - [ ] .ProcessRequiresRights
  - [ ] .JobRequiresRights
  - [ ] .CreateSecondExceptionChannel
  - [ ] .OverwriteClosedExceptionChannel
  - [ ] .ThreadReceive
  - [ ] .ProcessReceive
  - [ ] .ProcessDebuggerReceive
  - [ ] .JobReceive
  - [ ] .JobDebuggerReceive
  - [ ] .ExceptionResume
  - [ ] .ExceptionStateProperty
  - [ ] .ExceptionStatePropertyBadArgs
  - [ ] .ExceptionStrategy
  - [ ] .ExceptionStrategyBadArgs
  - [ ] .CloseChannelWithException
  - [ ] .CloseChannelWithoutException
  - [ ] .SkipClosedExceptionChannel
  - [ ] .TaskDeathClosesThreadExceptionChannel
  - [ ] .TaskDeathClosesProcessExceptionChannel
  - [ ] .TaskDeathClosesProcessDebugExceptionChannel
  - [ ] .TaskDeathClosesJobExceptionChannel
  - [ ] .TaskDeathClosesJobDebugExceptionChannel
  - [ ] .ThreadDeathWithExceptionInChannel
  - [ ] .ThreadDeathWithExceptionReceived
  - [ ] .ExceptionChannelOrder
  - [ ] .ExceptionChannelOrderWithSecondChanceDebugging
  - [ ] .DebugChannelClosedBeforeSecondChance
  - [ ] .ThreadLifecycleChannelExceptions
  - [ ] .ProcessLifecycleJobChannel
  - [ ] .ProcessLifecycleParentJobChannel
  - [ ] .ProcessStartExceptionDoesNotBubbleUp
  - [ ] .LifecycleExceptionsToDebugHandlersOnly
  - [ ] .LifecycleBlocking
  - [ ] .ReadWriteThreadStateFromThreadChannel
  - [ ] .ReadWriteThreadStateFromProcessChannel
  - [ ] .ReadWriteThreadStateFromProcessDebugChannel
  - [ ] .ReadWriteThreadStateFromJobChannel
  - [ ] .ReadWriteThreadStateFromParentJobChannel
  - [ ] .SyntheticExceptionReadWriteRegs
  - [ ] .KillThreadAndCloseExceptionRace
- [ ] ExceptionGetString
   - [ ] .AllOfEm

[1] Needs #104
[2] Needs #106

**Comment by benpigchu** [comment]
One thing that is missing: ProcessInfo has a field indicate is there a debugger channel attched.

**Comment by benpigchu** [comment]
A bug in current task.kill implementation: Job and process "terminated" too early. they should be really terminated when all childs are terminated.
Because of this, a call to process.exit do not trigger a ThreadExiting exception since the process debug channel is already shutdowned.

**Comment by benpigchu** [comment]
Although it is not well documented, but closing the last handle of a job seems should also kills the job(!)

**Comment by benpigchu** [comment]
The thread should be dying instead of dead when it is waiting for THREAD_EXITING exception resolves!

**Comment by benpigchu** [comment]
For `DefaultExceptionHandlerTest` , `DefaultExceptionHandlerTest.UnhandledHardwareException` pass now, and ` DefaultExceptionHandlerTest.UnhandledPolicyException` needs #106

**Comment by wangrunji0408** [comment]
## Note for running exception test

Build Fuchsia with customized option:

```sh
fx set bringup.x64 --with-base //src/zircon/tests/exception:exception-package
fx build
```

Run exception-test on Zircon shell:
```
/boot/test/exception-test -f *-ExceptionTest.SyntheticExceptionReadWriteRegs
```

Expected results:
```
[----------] Global test environment tear-down.
[==========] 47 tests from 2 test cases ran (5291 ms total).
[  PASSED  ] 42 tests
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] ExceptionTest.ReadWriteThreadStateFromThreadChannel
[  FAILED  ] ExceptionTest.ReadWriteThreadStateFromProcessChannel
[  FAILED  ] ExceptionTest.ReadWriteThreadStateFromProcessDebugChannel
[  FAILED  ] ExceptionTest.ReadWriteThreadStateFromJobChannel
[  FAILED  ] ExceptionTest.ReadWriteThreadStateFromParentJobChannel
5 FAILED TESTS
```
