### ISSUE TITLE
Implement task kill

### ISSUE THREAD

**Issue by wangrunji0408** [rcore-os/zCore#72]
Implement syscall:
- [ ] zx_task_kill

**Comment by xy-plus** [comment]
接单

**Comment by xy-plus** [comment]
放弃

**Comment by benpigchu** [comment]
Let me take this.

**Comment by benpigchu** [comment]
@xy-plus has an implementation in the task_kill branch.

The implementation in that branch do not pass the `Threads.KillSuspendedThread` case  [[test case code](https://fuchsia.googlesource.com/fuchsia/+/master/zircon/system/utest/core/threads/threads.cc#815)]

**Comment by benpigchu** [comment]
However, we should reset suspend_count to zero before waking waker, so that the `RunnableChecker` won't set waker again.

**Comment by benpigchu** [comment]
The code won't compile if we merge changes from #87, we should still use process_exit to remove the process from the job.

**Comment by benpigchu** [comment]
Now my fork were successfully merged into current master.
There are still two thing to implement: killing a blocked thread and killing the job.

**Comment by benpigchu** [comment]
To kill a blocked thread:

In zcore, we use `block_run` to block the thread. It do the following things:
1. lock the thread lock and replace the state
2. run the future
3. lock the thread lock again and recover the state

So, to kill a blocking thread, we need to check if the thread is dying in 1, stop the future running in 2, and check if the thread is dying again in 3.

If the thread was killed in `block_run` , I think we should make it returns a special error code (like ZxError::STOP) to indicate the thread is killed.

**Comment by wangrunji0408** [comment]
Also need to add another cancel token to wakeup the blocking thread?

**Comment by benpigchu** [comment]
Job killing is actually implemented by @xy-plus , so I simply add it to the syscall body

**Comment by benpigchu** [comment]
Seems there is a deadlock in the task kill implementation found on the CI
